export const JeonBuk = [
  {
    Gochang: {
      name: '고창군',
      areaCode: '37',
      sigunguCode: '1',
      reviewCount: '0',
      engarea: 'Gochang-gun',
      description:
        '시대를 거슬러가는 여행, 고창군. 1500년 역사를 지닌 사찰 선운사는 매년 9월 말이면 선운문화제가 열리는데 붉은 꽃무릇이 장관을 이룬다. 방장산을 둘러싼 고창읍성은 성곽을 따라 산책하기 좋으며, 고창 고인돌 박물관에 가면 선사시대의 흔적을 만날 수 있다. 봄이면 청보리밭으로, 가을이면 하얀 메밀꽃이 농장 전체를 가득 수놓는 청보리밭도 인기 코스!',
      hashtag: ['#해바라기밭', '#선운사', '#풍천장어'],
      tourcount: '150',
      tourdate: '3~6월',
      spec: '수박, 복분자, 풍천장어',
      mapy: 35.4356982163483,
      mapx: 126.702120365321,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FGochang.jpg?alt=media&token=06c4b3bc-3aa2-46a8-871f-4cf77e5a21ed',
    },
  },
  {
    Gunsan: {
      name: '군산시',
      areaCode: '37',
      sigunguCode: '2',
      reviewCount: '0',
      engarea: 'Gunsan-si',
      description:
        '1930년대 우리나라 근대역사를 고스란히 간직한 도시 군산. 근대문화유산 투어 코스를 따라 걷다보면 곳곳에 남아있는 일본식 주택과 근대건축물들을 쉽게 볼 수 있다. 2.5km 길이의 오래된 철도가 놓인 경암동 철길마을은 출사지로도 유명. 우리나라에서 가장 오래된 빵집, 전국 5대 짬뽕 맛집, 70년 역사의 호떡집 등 군산 맛집 먹방 여행도 추천한다.',
      hashtag: ['#이성당', '#새만금방조제', '#선유도'],
      tourcount: '323',
      tourdate: '6~12월',
      spec: '마늘, 메밀국수, 꽃게',
      mapy: 35.9674665619218,
      mapx: 126.736840487468,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FGunsan.gif?alt=media&token=6702544f-7338-4b63-941e-57c41d001c74',
    },
  },
  {
    Gimje: {
      name: '김제시',
      areaCode: '37',
      sigunguCode: '3',
      reviewCount: '0',
      engarea: 'Gimje-si',
      description:
        '다양한 사찰을 만날 수 있는 김제시. 독특한 형태의 부도를 지닌 금산사와 바다를 바라보고 있는 망해사, 독특한 이름을 지닌 귀신사까지 특색 있는 사찰들이 자리하고 있다. 소설가 조정래의 장편소설 아리랑의 이야기가 담긴 아리랑 문학관도 함께 방문해보면 좋다.',
      hashtag: ['#벽골제', '#금산사', '#오늘여기'],
      tourcount: '111',
      tourdate: '6~10월',
      spec: '호두, 고추장, 쌀',
      mapy: 35.8035816671869,
      mapx: 126.88064623757,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FGimje.jpg?alt=media&token=9a19bc2c-6423-495b-85a5-4de9e5e4b9f2',
    },
  },
  {
    Namwon: {
      name: '남원시',
      areaCode: '37',
      sigunguCode: '4',
      reviewCount: '0',
      engarea: 'Namwon-si',
      description:
        '춘향의 사랑이 남겨진 남원. 남원의 대표 광한루는 춘향과 몽룡의 사랑이 시작된 곳으로 연못 위에 세워진 오작교가 운치를 더한다. 5가지의 테마로 꾸며진 춘향 테마파크와 작가 최명희의 대하소설의 무대가 되었던 <혼불> 문학관도 가볼 만하다.지리산 바래봉은 철쭉제가 열리는 봄에 여행하기 좋다.',
      hashtag: ['#춘향테마파크', '#광한루원', '#남원항공우주천문대'],
      tourcount: '208',
      tourdate: '9~12월',
      spec: '더덕, 고추, 참숯',
      mapy: 35.4163627529983,
      mapx: 127.390396427422,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FNamWon.webp?alt=media&token=58aece15-55b1-4ec3-87e5-6dd56d050b6a',
    },
  },
  {
    Muju: {
      name: '무주군',
      areaCode: '37',
      sigunguCode: '5',
      reviewCount: '0',
      engarea: 'Muju-gun',
      description:
        '겨울 대표 여행지 무주군. 겨울을 대표하는 설산인 덕유산이 있기 때문이다. 덕유산에 위치한 스키장은 코스의 난이도가 다양하게 나뉘어 있어 실력에 따라 즐길 수 있다는 게 큰 장점이다. 8월 말에서 9월 초에 열리는 반딧불축제는 무주에서 볼 수 있는 신비로운 여정 중 하나! 평소 와인을 즐긴다면 머루와인동굴에 들러 시음해보는 것도 좋다.',
      hashtag: ['#태권도원', '#덕유산', '#무주반디랜드'],
      tourcount: '174',
      tourdate: '8~12월',
      spec: '산수유, 메밀, 곰취',
      mapy: 35.4163627529983,
      mapx: 127.390396427422,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FMuju.jpg?alt=media&token=624e8f31-615b-426e-9981-a9ac2d2acd11',
    },
  },
  {
    Buan: {
      name: '부안군',
      areaCode: '37',
      sigunguCode: '6',
      reviewCount: '0',
      engarea: 'Buan-gun',
      description:
        '일몰이 아름다운 부안군. 격포항과 변산 모항은 해 질 녘 석양이 일품이다. 특히 변산모 항에서 조금 떨어진 솔섬은 사진작가도 많이 찾는 일몰 포인트 지점이며, 변산반도국립공원을 대표하는 채석강은 겹겹이 포개놓은 듯한 해식절벽으로 유명하다. 소금밭에서 작업하는 염부의 모습이 인상 깊은 곰소염전도 이 지역에서만 볼 수 있는 장면!',
      hashtag: ['#곰소염전', '#채석강', '#변선해수욕장'],
      tourcount: '188',
      tourdate: '6~12월',
      spec: '양파, 참외, 깻잎',
      mapy: 35.7316577924649,
      mapx: 126.733011321782,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FBuan.jpg?alt=media&token=fb51f2a8-72ae-4eb8-bed3-7548e6b072ae',
    },
  },
  {
    Sunchang: {
      name: '순창군',
      areaCode: '37',
      sigunguCode: '7',
      reviewCount: '0',
      engarea: 'Sunchang-gun',
      description:
        '순창하면 빼놓을 수 없는 고추장! 전통 장류 산업이 발달된 고장인 만큼 그에 관한 다양한 체험이 마련되어 있다. 전통고추장 정보화 마을에서는 고추장 만들기 체험도 가능하며 순창장류 박물관에는 장류 문화의 모든 것이 모여있다. 가을 단풍과 4월 초 만개하는 산벚꽃으로 유명한 강천산은 등산뿐 아니라 산책을 즐기기에도 좋아 인기가 급부상하고 있는 산이다.',
      hashtag: ['#강천산', '#화양연화', '#푸드사이언스관'],
      tourcount: '92',
      tourdate: '6~12월',
      spec: '고추장, 찰보리, 구기자',
      mapy: 35.3744452332964,
      mapx: 127.137364881069,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FSunchang.jfif?alt=media&token=88987aba-7179-43fa-b223-73ab52ccb027',
    },
  },
  {
    Wanju: {
      name: '완주군',
      areaCode: '37',
      sigunguCode: '8',
      reviewCount: '0',
      engarea: 'Wanju-gun',
      description:
        '완주하면 대둔산을 가장 먼저 떠올리게 된다. 대둔산의 명물인 케이블카를 타면 5분 만에 구름다리 인근까지 닿을 수 있기 때문이다. 고산 자연휴양림과 대아 수목원은 가벼운 산책코스로도 좋다.',
      hashtag: ['#아원', '#고산자연휴양림', '#대둔산'],
      tourcount: '188',
      tourdate: '6~12월',
      spec: '양배추, 청과, 매실',
      mapy: 35.9048145963415,
      mapx: 127.162119017463,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FWanju.jfif?alt=media&token=d81b3bc3-4095-4483-85fe-f93375e6b5e7',
    },
  },
  {
    Iksan: {
      name: '익산시',
      areaCode: '37',
      sigunguCode: '9',
      reviewCount: '0',
      engarea: 'Iksan-si',
      description:
        '우리나라에서 가장 오래된 기차역인 춘포역은 이제 문을 닫았지만 추억 속 간이역의 운치가 남아 있어 잠시 쉬어가기 좋다. 백제시대 유적으로 세계유산으로 등록되어있는 왕궁리유적과 미륵사지도 천천히 둘러보면 좋고, 당일치기로 익산을 둘러볼 예정이라면 저렴한 가격의 시티투어도 추천한다.',
      hashtag: ['#고스락', '#국립익산박물관', '#미륵사지'],
      tourcount: '175',
      tourdate: '6~12월',
      spec: '어리굴비, 대추, 생면',
      mapy: 35.9482628600199,
      mapx: 126.957744486694,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FIksan.jpg?alt=media&token=b67352a2-377e-42b3-8f20-9fbea5d9f77d',
    },
  },
  {
    Imsil: {
      name: '임실군',
      areaCode: '37',
      sigunguCode: '10',
      reviewCount: '0',
      engarea: 'Imsil-gun',
      description:
        '한국 치즈의 발상지 임실. 가장 대표적인 임실 치즈마을에서는 치즈 만들기와 초지 낙농체험이 가능하다. 직접 피자도 만들며 맛보는 재미에 아이와 함께 가족단위로 찾는 경우가 많다. 거대한 인공호수 옥정호는 새벽 물안개가 피어나는 풍경이 아름다워 출사지로 유명해졌다. 옥정호를 한눈에 내려다볼 수 있는 국사봉 전망대에 오르는 것도 관망 포인트!',
      hashtag: ['#임실치즈', '#임실치즈테마파크', '#옥정호'],
      tourcount: '99',
      tourdate: '6~12월',
      spec: '치즈, 송이버섯, 밤',
      mapy: 35.9482628600199,
      mapx: 126.957744486694,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FImsil.jpg?alt=media&token=d14c5ba4-b0fb-4f31-9580-77b42726ab4a',
    },
  },
  {
    Jangsu: {
      name: '장수군',
      areaCode: '37',
      sigunguCode: '11',
      reviewCount: '0',
      engarea: 'Jangsu-gun',
      description:
        '전라북도의 숨겨진 여행지 장수군. 많은 이들에게 알려지지 않았지만 잔잔한 자연 풍경과 우리의 전통을 만날 수 있는 곳이다. 대표적으로 논개의 충절을 느낄 수 있는 논개사당 의암사와 논개 생가가 있다. 와룡자연휴양림은 물놀이장과 잔디구장 등이 마련되어 있어 아이들과 함께 하룻밤을 즐기기에 좋다. 장안산 하면 억새 군락이 유명해 가을 산행으로 제격이다.',
      hashtag: ['#와룡자연휴양림', '#억새', '#사과축제'],
      tourcount: '87',
      tourdate: '9~11월',
      spec: '사과, 석류, 순두부',
      mapy: 35.6473551301164,
      mapx: 127.52161241409,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FJangsu.jpg?alt=media&token=da595aeb-976a-4728-9661-8b04f536e259',
    },
  },
  {
    Jeonju: {
      name: '전주시',
      areaCode: '37',
      sigunguCode: '12',
      reviewCount: '0',
      engarea: 'Jeonju-si',
      description:
        "한국의 멋이 살아있는 전주. 도심 한복판에 자리한 한옥마을에 들어서면 시대를 거슬러가는 기분이다. '경사스러운 터에 지어진 궁궐'이란 의미의 경기전에 들어서면 대나무가 서로 부대끼며 내는 소리에 귀 기울이게 된다. 전주 야경투어 명소의 대표인 전동성당과 한옥마을을 한눈에 내려다볼 수 있는 오목대 역시 빼놓을 수 없는 곳. 마을 전체가 미술관인 자만 벽화마을은 전주의 대표 포토 존이다.",
      hashtag: ['#전주동물원', '#전주한옥마을', '#모주'],
      tourcount: '419',
      tourdate: '1~12월',
      spec: '콩나물, 막걸리, 비빔밥',
      mapy: 35.8240731508775,
      mapx: 127.148143800621,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FJeonju.jpg?alt=media&token=a660d577-8a61-4d8f-b221-57d39e743bbc',
    },
  },
  {
    Jeongeup: {
      name: '정읍시',
      areaCode: '37',
      sigunguCode: '13',
      reviewCount: '0',
      engarea: 'Jeongeup-si',
      description:
        '최고의 가을 풍경을 자부하는 정읍. 내장산은 우리나라 제1의 단풍 관광지로 뽑힐 만큼 가을 대표 명소이다. 내장사 역시 가을이 아름다운 사찰로 손꼽히며, 옥정호 구절초 테마공원에 구절초 꽃이 피어나면 가을이 다가옴을 알리는 구절초 축제가 열린다.',
      hashtag: ['#내장산', '#구절초테마공원', '#전설의쌍화차거리'],
      tourcount: '129',
      tourdate: '6~12월',
      spec: '자두, 한우, 건강보리',
      mapy: 35.5698780259932,
      mapx: 126.856005647439,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FJeongeup.webp?alt=media&token=997a8579-7235-48a8-b513-fa132b208d81',
    },
  },
  {
    Jinan: {
      name: '진안군',
      areaCode: '37',
      sigunguCode: '14',
      reviewCount: '0',
      engarea: 'Jinan-gun',
      description:
        '우리나라에서 가장 늦은 벚꽃을 볼 수 있다는 진안 마이산. 진안의 대표 관광지로 손꼽히는 마이산은 알수록 더 신비로운 매력에 빠져든다. 누구보다 오래도록 마주하는 벚꽃과의 여행에 설레다가도 암벽에 움푹 움푹 패어있는 거대한 타포니 지형에 시선을 빼앗기고, 가장 기가 세다는 천지탑은 100여 년이 넘도록 그 모진 세월을 견뎌낸 걸 보면 신기하다 못해 신비로움에 사로잡힌다. 익숙함과 새로움이 공존하는 봄 여행을 꿈꾼다면 전라북도 진안군을 추천한다.',
      hashtag: ['#마이산', '#구봉산', '#운일암반일암'],
      tourcount: '117',
      tourdate: '3~6월',
      spec: '청어, 약수터물, 명태',
      mapy: 35.7917723036092,
      mapx: 127.424865465441,
      image:
        'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FJinan.jpg?alt=media&token=c3cf0d04-6c33-4ac1-9384-1ef37ee7cd4a',
    },
  },
];

export const JeonNam = [
  {
    Gangjin: {
      name: '강진군',
      areaCode: '38',
      sigunguCode: '1',
      reviewCount: '0',
      engarea: 'Gangjin-gun',
      description:
        '2월부터 터트린 꽃망울이 3월이 되면 낙화하기 시작해 땅과 하늘이 붉게 물드는 백련사 동백숲. 그 옆으로 이어지는 고개를 넘어가면 이어지는 다산 정약용 선생의 유배 생활지이자 학문의 꽃이 피었던 다산초당이 있다. 약 500여 년 동안 고려청자의 본향으로서 청자 문화를 알리기 위한 강진청자축제가 매년 열리며 고려청자 박물관에 방문하면 다양한 청자를 한눈에 둘러볼 수 있다.',
      hashtag: ['#다산초당', '#백련사', '#고려청자박물관'],
      tourcount: '120',
      tourdate: '9~12월',
      spec: '홍어, 고추장게장, 돌산갓김치',
      mapy: 34.6420615268858,
      mapx: 126.767213471898,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FGangjin.jpg?alt=media&token=81e29e34-2b1b-44eb-afb6-52761246cbfc',
    },
  },
  {
    Goheung: {
      name: '고흥군',
      areaCode: '38',
      sigunguCode: '2',
      reviewCount: '0',
      engarea: 'Goheung-gun',
      description:
        '다도해를 품은 항공 우주도시 전남 고흥군. 빼어난 기암절벽이 연속해서 펼쳐지는 나로도 해상 경관은 절로 감탄이 나오게 한다. 나로우주센터와 가까운 우주발사 전망대는 해안절경이 뛰어나 지역의 랜드 마크로 자리매김했다. 맑고 깨끗한 천혜의 자연 속에서 재배된 유자와 석류는 고흥의 대표 자랑거리. 참장어는 남해안 일부 지역에서만 생산되므로 맛보고 가지 않으면 후회한다는 말이 있을 정도로 별미로 꼽힌다.',
      hashtag: ['#나로우주센터', '#치유의숲', '#남열해돋이전망대'],
      tourcount: '133',
      tourdate: '6~12월',
      spec: '산낙지, 송어회, 대추방울토마토',
      mapy: 34.6110820210903,
      mapx: 127.284968746855,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FGoheung.jpg?alt=media&token=26bd8a83-41e0-4aa1-9c63-b338880a7644',
    },
  },
  {
    Gokseong: {
      name: '곡성군',
      areaCode: '38',
      sigunguCode: '3',
      reviewCount: '0',
      engarea: 'Gokseong-gun',
      description:
        '전국에서 가장 많은 종류의 장미가 있는 섬진강 기차마을에서 레일바이크를 타고 강변을 따라 달리다 보면 아름다운 경관들을 마주하게 된다. 섬진강 일대에서는 캠핑뿐만 아니라 각종 수상레포츠를 즐길 수 있고 별미인 은어회와 참게매운탕은 또 다른 즐거움을 준다. 트레킹 코스로 각광받고 있는 섬진강 볼레길을 따라 걷거나 자전거를 대여해 달리다 보면 몸과 마음이 상쾌해진다.',
      hashtag: ['#섬진강레일바이크', '#심청한옥마을', '#압록유원지'],
      tourcount: '111',
      tourdate: '3~6월',
      spec: '참나무김치, 감자, 참숯',
      mapy: 35.2820258392354,
      mapx: 127.291929639637,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FGoksung.jpg?alt=media&token=9f818d3d-ebdf-437b-b803-a1ed86b8ff8c',
    },
  },
  {
    Gwangyang: {
      name: '광양시',
      areaCode: '38',
      sigunguCode: '4',
      reviewCount: '0',
      engarea: 'Gwangyang-si',
      description:
        "매년 봄, 새하얀 매화로 뒤덮이는 매화마을은 섬진강 풍경과 함께 어우러져 전국의 아름다운 매화 명소 중 한 곳으로 꼽힌다. 우리나라에서 철쭉을 제일 먼저 볼 수 있는 백운산 국사봉 또한 빠질 수 없는 봄꽃 명소다. 밤이 되면 이순신대교, 광양항, 제철소가 있는 광양만에는 불빛들로 가득해 구봉산 전망대에서 바라보는 야경은 황홀하기 그지없다. '천하일미 마로 화적'으로 일컬어질 정도로 널리 알려진 광양불고기는 광양의 상징하는 대표 음식이다.",
      hashtag: ['#매화마을', '#구봉산전망대', '#느랭이골'],
      tourcount: '98',
      tourdate: '3~6월',
      spec: '불고기, 딸기, 참매생이',
      mapy: 34.9404252535168,
      mapx: 127.695930772808,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FGwangyang.jpg?alt=media&token=59548bb4-706e-42e9-9bad-c6a22912c850',
    },
  },
  {
    Gurye: {
      name: '구례군',
      areaCode: '38',
      sigunguCode: '5',
      reviewCount: '0',
      engarea: 'Gurye-gun',
      description:
        "봄꽃의 향연이 펼쳐지는 전남 구례군. 지리산 자락 아래에는 샛노란 산수유꽃이 만개해 매년 봄 산수유꽃 축제가 열린다. 섬진강 변에는 벚꽃길이 조성되어 있어 드라이브하기 좋은 최적의 코스로 한국에서 가장 아름다운 길 100선에 선정되기도 했다. 구례 5일 장은 화개장터와 함께 대표적인 시골장으로서 봄이면 지리산에서 캔 각종 산나물과 들나물이 단연 인기를 끌고 있다.",
      hashtag: ['#구례산수유마을', '#구례자연드림파크', '#섬진강대나무숲길'],
      tourcount: '135',
      tourdate: '3~6월',
      spec: '산수유, 유자, 향토술',
      mapy: 35.202496361707,
      mapx: 127.46270363657,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FGurye.jpg?alt=media&token=217b9a16-07f7-4186-8292-3807e03132f9',
    },
  },
  {
    Naju: {
      name: '나주시',
      areaCode: '38',
      sigunguCode: '6',
      reviewCount: '0',
      engarea: 'Naju-si',
      description:
        "삼국시대에 온 듯한 기분이 들게 하는 나주 영상 테마파크는 드라마, 영화 촬영지이기도 하지만 당시의 역사, 문화를 체험할 수 있는 곳이다. 성균관 다음으로 큰 조선시대 교육 시설인 나주 향교는 역사적, 건축학적 가치가 크며 해마다 여름에 서당이 개설되고 시민들의 전통 혼례식장으로도 이용된다. 푹 끓인 곰탕과 톡 쏘는 맛이 일품인 홍어는 나주를 상징하는 음식인 만큼 먹어보는 것을 추천한다.",
      hashtag: ['#국립나주박물관', '#금성관', '#나주영상테마파크'],
      tourcount: '133',
      tourdate: '9~12월',
      spec: '곰탕, 홍어, 떡갈비',
      mapy: 35.0158976865702,
      mapx: 126.71082925505,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FNaju.png?alt=media&token=b75f270f-b321-4041-9ac5-c97c6b7b87ec',
    },
  },
  {
    Damyang: {
      name: '담양군',
      areaCode: '38',
      sigunguCode: '7',
      reviewCount: '0',
      engarea: 'Damyang-gun',
      description:
        "초록 내음 가득한 슬로시티 전남 담양군. 하늘을 찌를 듯한 대나무 그리고 맑은 댓잎의 향기가 가득한 죽녹원은 담양의 대표 관광 명소. 가로수들이 일렬로 서있는 메타세쿼이아 길은 이국적인 풍경을 자랑한다. 아시아 최초의 슬로시티 창평 삼지천 마을의 고즈넉한 한옥, 운치 있는 골목길 그리고 각종 슬로푸드들을 보고 있노라면 타임머신을 타고 옛날 여행을 하는 기분이 들게 만든다.",
      hashtag: ['#죽녹원', '#담양관방제림', '#메타세콰이어길'],
      tourcount: '163',
      tourdate: '6~12월',
      spec: '죽순, 산채비빔밥, 더덕',
      mapy: 35.3212107735503,
      mapx: 126.988210711052,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FDamyang.jpg?alt=media&token=ef4d9eb2-5bea-4206-9187-049508d6ed5c',
    },
  },
  {
    Mokpo: {
      name: '목포시',
      areaCode: '38',
      sigunguCode: '8',
      reviewCount: '0',
      engarea: 'Mokpo-si',
      description:
        "아름다운 한 폭의 동양화를 연상시키는 유달산에서 다도해의 경관을 한눈에 감상할 수 있다. 때묻지 않은 자연을 간직한 사랑의 섬 외달도는 전국에서 휴양하기 좋은 섬 30위 안에 선정될 만큼 아름다운 바다와 해변이 특징이다. 목포 평화광장 앞 바다에는 음악에 맞춰 빛과 물이 어우러지는 세계 최대의 춤추는 바다분수가 있어 이색적인 볼거리를 제공하고 있다. 갯벌 속의 인삼이라 불리는 세 발 낙지는 목포의 대표적인 토산품 중 하나이며 일부 지역에서만 잡히는 지역 특산품이다.",
      hashtag: ['#씨엘비베이커리', '#목포해상케이블카', '#갓바위'],
      tourcount: '278',
      tourdate: '9~12월',
      spec: '어묵, 세발낙지, 장어',
      mapy: 34.8118309400519,
      mapx: 126.392235351241,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FMokpo.jpg?alt=media&token=4f8a07ee-9801-468b-9f43-916a3af33e78',
    },
  },
  {
    Muan: {
      name: '무안군',
      areaCode: '38',
      sigunguCode: '9',
      reviewCount: '0',
      engarea: 'Muan-gun',
      description:
        "매년 7-8월 경, 꽃 중의 군자로 불리는 백련을 마음껏 감상할 수 있는 회산백련지는 동양 최대의 백련 자생지라고 불린다. 조수간만의 차가 심하여 펼쳐지는 끝없이 넓은 백사장과 보호림으로 지정된 해송 숲이 조화를 이루는 톱머리 해수욕장에서 낚시와 피서를 즐길 수 있다. 무안 지역의 갯벌은 게르마늄이 다량 함유되어 있어 이곳에서 잡힌 세 발 낙지는 별미로 꼽힌다.",
      hashtag: ['#톱머리해수욕장', '#무안황토갯벌', '#홀통해수욕장'],
      tourcount: '105',
      tourdate: '6~8월',
      spec: '멸치, 세발낙지, 청송도',
      mapy: 34.7888170541041,
      mapx: 126.384450031799,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FMuan.jpg?alt=media&token=98f38235-2d14-44ca-b465-b474aae2fa93',
    },
  },
  {
    Boseong: {
      name: '보성군',
      areaCode: '38',
      sigunguCode: '10',
      reviewCount: '0',
      engarea: 'Boseong-gun',
      description:
        "그윽한 향이 가득한 푸르른 녹차수도 보성군. 국내에서 가장 오래된 녹차 재배지로서 보성차밭은 수려한 자연경관을 자랑하며 매년 5월 보성다향대축제가 개최된다. 고운 은빛 모래와 소나무들이 숲을 이룬 율포해수욕장 근처에 보성 녹차 잎을 우려낸 해수 녹차탕이 있어 휴식을 취할 수 있다. 벌교꼬막이라는 고유명사가 붙을 만큼 해마다 꼬막 축제가 열려 신선하고 맛있는 꼬막 요리를 맛볼 수 있다.",
      hashtag: ['#대한다원보성녹차밭', '#비봉공룡공원', '#한국차박물관'],
      tourcount: '114',
      tourdate: '9~12월',
      spec: '녹차, 꼬막, 미나리',
      mapy: 34.7714427538727,
      mapx: 127.079946438917,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FBoseong.jpg?alt=media&token=d958a92f-6d19-422f-a53c-c0d4b4d4d1de',
    },
  },
  {
    Suncheon: {
      name: '순천시',
      areaCode: '38',
      sigunguCode: '11',
      reviewCount: '0',
      engarea: 'Suncheon-si',
      description:
        "살아숨쉬는 생태 수도 전남 순천시. 매년 깊어지는 가을마다 세계 5대 습지이자 철새들의 도래지인 순천만 습지의 갈대밭은 더욱 몽환적인 모습으로 무장한다. 이를 보호하고자 만든 순천만 국가 정원에서는 다양한 생태 식물들을 관찰할 수 있어 또 다른 자연의 아름다움을 느낄 수 있다. 구불구불한 리아스식 해안선을 따라 드라이브할 수 있는 와온해변은 일몰이 아름답기로 유명하며 이곳의 마을에서는 어촌체험도 가능하다. 추억을 떠올리게 하는 순천 드라마 세트장은 60-80년대의 모습을 완벽히 재현하고 있어 떠오르는 관광 명소다.",
      hashtag: ['#순천만국가공원', '#낙안읍성', '#와온해변'],
      tourcount: '237',
      tourdate: '6~12월',
      spec: '오징어, 연어, 바지락',
      mapy: 34.9506097806669,
      mapx: 127.487382934915,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FSuncheon.jpg?alt=media&token=3f98f9a2-e869-4e6a-ad0e-8b54c5602bef',
    },
  },
  {
    Shinan: {
      name: '신안군',
      areaCode: '38',
      sigunguCode: '12',
      reviewCount: '0',
      engarea: 'Shinan-gun',
      description:
        "살다도해의 수려한 자연경관이 펼쳐지는 전남 신안군. 해 질 녘 섬이 붉게 물든다 하여 붙여진 홍도는 이름처럼 일몰이 아름다운 섬이다. 유배지로 이름을 떨쳤던 흑산도는 일주 도로가 조성되어 있어 섬 전역을 편리하게 둘러볼 수 있다. 하트해변이 있는 비금도와 최서남단의 섬 가거도까지, 어느 하나 빼놓을 수 없는 신안군의 대표 여행지이다.",
      hashtag: ['#천사섬', '#퍼플교', '#하트해변'],
      tourcount: '126',
      tourdate: '6~12월',
      spec: '홍합, 삼치, 매화백년초',
      mapy: 34.833553882858,
      mapx: 126.351614243402,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FShinan.jpg?alt=media&token=74efa75c-4114-4817-b5e7-58096b2dedac',
    },
  },
  {
    Yeosu: {
      name: '여수시',
      areaCode: '38',
      sigunguCode: '13',
      reviewCount: '0',
      engarea: 'Yeosu-si',
      description:
        "국제 해양관광의 중심 전남 여수시. 3천여 그루의 동백나무로 가득 찬 붉은 섬 오동도는 웰빙 트래킹 코스를 갖추고 있어 한층 더 운치 있다. 해상 케이블카를 타면 마치 바다 위를 걷는 듯한 느낌이 들며 탁 트인 바다 전망을 감상할 수 있다. 노래 가사에도 나오는 낭만적이고 황홀한 여수의 밤바다는 돌산대교와 음악분수가 함께 어우러져 멋진 야경을 선사한다. 공식 밥도둑 게장백반과 돌산 갓김치, 갈치조림 등 풍부한 먹거리까지 갖춘 인기 만점 관광지!",
      hashtag: ['#오동도', '#여수해상케이블카', '#아쿠아플라넷'],
      tourcount: '535',
      tourdate: '1~12월',
      spec: '선지해표어, 산국, 박하사탕',
      mapy: 34.7604010648246,
      mapx: 127.662331251572,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FYeosu.jpg?alt=media&token=4421ef22-778c-479c-bd22-e9024b7fa48f',
    },
  },
  {
    Yeonggwang: {
      name: '영광군',
      areaCode: '38',
      sigunguCode: '16',
      reviewCount: '0',
      engarea: 'Yeonggwang-gun',
      description:
        "기암괴석, 광활한 갯벌 그리고 불타는 석양이 만나 황홀한 풍경을 연출하는 백수해안도로는 환상의 드라이브 코스. 전남에서 가장 높은 바다 전망대인 칠산타워에서 칠산 앞바다의 비경과 낙조를 한눈에 감상할 수 있다. 금강산도 식후경! 법성포 굴비와 청보리 한우로 입과 배까지 즐겁게 만들어준다면 금상첨화.",
      hashtag: ['#가마미해수욕장', '#영광굴비거리', '#영광칠산타워'],
      tourcount: '99',
      tourdate: '6~12월',
      spec: '굴비, 한우, 참마',
      mapy: 35.2771900332592,
      mapx: 126.512013797425,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FYeonggwang.jpg?alt=media&token=940aaf1c-6b93-40fb-a176-2d687f7ff523',
    },
  },
  {
    Yeongam: {
      name: '영암군',
      areaCode: '38',
      sigunguCode: '17',
      reviewCount: '0',
      engarea: 'Yeongam-gun',
      description:
        "기(氣)의 고장 전남 영암군. 영암의 자존심이자 기둥인 월출산에서의 산행을 통해 자연의 활기를 느낄 수 있다. 빙설 옥수가 흐르는 월출산 용추골에 자리한 기찬랜드는 계곡을 흐르는 자연수를 활용하여 새롭게 조성된 대표 관광명소다. 월출산의 기(氣)를 느끼고 싶다면 친자연 웰빙 산책로인 기찬묏길을 따라 걸으며 심신을 단련해보는 것도 좋다.",
      hashtag: ['#왕인박사유적지', '#월출산', '#영암곤충박물관'],
      tourcount: '77',
      tourdate: '6~10월',
      spec: '떡, 산삼, 호떡',
      mapy: 34.8000591144732,
      mapx: 126.696762590551,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FYeongam.jpg?alt=media&token=0f2d4441-16a2-4c5f-b9db-2604325e9472',
    },
  },
  {
    Wando: {
      name: '완도군',
      areaCode: '38',
      sigunguCode: '18',
      reviewCount: '0',
      engarea: 'Wando-gun',
      description:
        "시간이 느리게 흘러가는 완도군. 청산도는 아시아 최초로 슬로시티에 선정된 섬답게 4월 한 달 간 '청산도 느리게 걷기 축제'를 열며 느림의 철학을 전파하고 있다. 다도해상 국립공원에 속하는 보길도는 윤선도의 <어부사시사>가 완성된 무대이기도 하다. 그 밖에 소완도, 금강도 등 잘 알려지지는 않았지만 자연 경관이 수려한 섬들을 많이 보유하고 있다.",
      hashtag: ['#명사십리해수욕장', '#청산도', '#금당도'],
      tourcount: '122',
      tourdate: '3~6월',
      spec: '김, 곶감, 오디',
      mapy: 34.3109789170971,
      mapx: 126.754998729552,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FWando.jpg?alt=media&token=f01c98d3-5c29-4174-85eb-56b6c9e859e1',
    },
  },
  {
    Jangseong: {
      name: '장성군',
      areaCode: '38',
      sigunguCode: '19',
      reviewCount: '0',
      engarea: 'Jangseong-gun',
      description:
        "학문과 선비의 고장 전남 장성군. 매년 봄, 소설 속 주인공으로 알려진 민중의 영웅 홍길동을 테마로 하는 축제가 황룡강변의 유채꽃을 배경으로 열린다. 울긋불긋 오색단풍으로 유명한 백양사는 천연기념물 매화 중 하나이자 국내에 4그루뿐인 고불매가 만개하는 곳이기도 하다. 치유의 숲이라 불리는 축령산 편백나무숲은 산림욕을 통해 잠시 일상에서의 스트레스를 내려놓을 수 있다.",
      hashtag: ['#백양사', '#축령산', '#장성댐'],
      tourcount: '78',
      tourdate: '3~6월',
      spec: '참외, 사과, 청포도',
      mapy: 35.3018576771354,
      mapx: 126.784918877012,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FJangseong.jpg?alt=media&token=29512fd8-b26b-4a4b-ba36-b49ee768f51c',
    },
  },
  {
    Jangheung: {
      name: '장흥군',
      areaCode: '38',
      sigunguCode: '20',
      reviewCount: '0',
      engarea: 'Jangheung-gun',
      description:
        "자연과 더불어 숨 쉬는 건강 휴양촌 장흥군. 전국 최초의 주말 관광 시장인 정남진 장흥 토요시장에서 한우, 키조개, 표고버섯을 삼합으로 즐길 수 있다. 호남 5대 명산 중 하나인 천관산의 아름다운 억새밭 장관은 마치 한 폭의 그림 같다. 약 3만여 평의 유채꽃과 메밀밭이 조성된 선학동에서는 봄에는 유채향, 가을에는 메밀향이 코 끝을 간지럽힌다. 편백 나무의 피톤치드향과 천연 소금을 이용한 피부질환 치유공간이 있는 편백숲 우드랜드는 떠오르는 명소.",
      hashtag: ['#편백나무숲', '#전망대', '#천관산'],
      tourcount: '102',
      tourdate: '3~10월',
      spec: '한우, 키조개, 표고버섯',
      mapy: 34.6816120675641,
      mapx: 126.907058431105,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FJangheung.jpg?alt=media&token=43ed9e24-5c28-4ff8-810c-c6eae46ef06a',
    },
  },
  {
    Jindo: {
      name: '진도군',
      areaCode: '38',
      sigunguCode: '21',
      reviewCount: '0',
      engarea: 'Jindo-gun',
      description:
        "우리나라에서 세 번째로 큰 섬 진도. 진도군 여행의 일번지는 바로 운림산방이다. 풍류를 엿볼 수 있는 곳으로 단풍이 물드는 가을이면 더욱 운치를 더한다. 진도에 가서 놓쳐선 안되는 것이 바로 낙조인데, 세방 낙조 전망대와 진도대교 전망대가 일몰 포인트 지점이다. 매년 4월에 열리는 진도 신비의 바닷길 축제에서 한국판 모세의 기적을 직접 눈으로 확인해보는 것을 추천한다.",
      hashtag: ['#운림산방', '#진도항', '#진도신비의바닷길'],
      tourcount: '110',
      tourdate: '3~10월',
      spec: '선문어, 트러플, 굴',
      mapy: 34.486828620348,
      mapx: 126.263446186439,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FJindo.jpg?alt=media&token=0bcb802c-7112-4da3-a7e5-dd617b24f87f',
    },
  },
  {
    Hampyeong: {
      name: '함평군',
      areaCode: '38',
      sigunguCode: '22',
      reviewCount: '0',
      engarea: 'Hampyeong-gun',
      description:
        "자연과 조화를 이룬 생태관광의 메카 함평군. 유채꽃 물결 사이로 날갯짓하는 나비들의 모습을 볼 수 있는 '함평 나비 대축제'가 매년 5월에 열린다. 공원 천지가 홍색 치마를 두른 듯한 장관이 펼쳐지는 용천사 꽃무릇공원은 관광객으로 하여금 탄성을 자아내게 만든다. 가을의 다른 정취를 느끼고 싶다면 국화 향기 가득한 엑스포공원에 방문해보는 것을 추천한다.",
      hashtag: ['#돌머리해수욕장', '#나비축제', '#용천사'],
      tourcount: '62',
      tourdate: '3~8월',
      spec: '당근, 더덕, 고추',
      mapy: 35.0659111691242,
      mapx: 126.516624840635,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FHampyeong.jpg?alt=media&token=6fc821fa-a6ce-4871-9836-4f45571afb5f',
    },
  },
  {
    Haenam: {
      name: '해남군',
      areaCode: '38',
      sigunguCode: '23',
      reviewCount: '0',
      engarea: 'Haenam-gun',
      description:
        "우리나라의 최남단이자 전남 최대 군인 해남군. 국토순례길의 시작과 끝을 모두 품은 땅끝마을에서의 백미는 전망대에 올라 일출을 보는 것이다. 남해안 쪽빛 바다의 아름다움을 더욱 생생하게 느끼고 싶다면 모노레일 카에 탑승하면 된다. 단 13척의 배로 왜군을 물리친 충무공 이순신 장군의 발자취를 울돌목 명량대첩축제에서 만날 수 있으며 거북선 또한 체험 가능하다.",
      hashtag: ['#대흥사', '#해남공룡박물관', '#땅끝전망대'],
      tourcount: '134',
      tourdate: '6~12월',
      spec: '선초고추, 대나무새우, 참외',
      mapy: 34.5735165884839,
      mapx: 126.599270065365,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FHaenam.jpg?alt=media&token=97727906-e6a4-4e9c-9e93-d921e916e4e9',
    },
  },
  {
    Hwasun: {
      name: '화순군',
      areaCode: '38',
      sigunguCode: '24',
      reviewCount: '0',
      engarea: 'Hwasun-gun',
      description:
        "방랑 시인 김삿갓, 다산 정약용 등 시인 묵객들의 발길이 끊이지 않았던 화순 적벽은 천혜의 장관을 연출하며 매년 10월 말 경에 적벽 문화제가 열린다. 유네스코 세계문화유산에 등재되어 가치를 인정받고 있는 고인돌 유적지는 지역민의 자긍심을 고취시키고 있다. 한국의 알프스라 불리는 만연산 철쭉공원은 봄이 되면 분홍색 철쭉 옷을 입어 눈을 뗄 수 없게 만든다.",
      hashtag: ['#세량제', '#무등산양떼목장', '#백아산썰매장'],
      tourcount: '117',
      tourdate: '9~12월',
      spec: '산수유, 청어, 사과',
      mapy: 35.0645119791204,
      mapx: 126.986502436773,
      image: 'https://firebasestorage.googleapis.com/v0/b/everest-project-ef02a.appspot.com/o/Cities%2FHwasoon.jfif?alt=media&token=12a50bce-0b9f-445c-9441-88d0d3b7a0de',
    },
  },
];
