// 메인 페이지 테마 배너

import { ListItem } from '../../types/ThemeType';

// 리스트 아이템 데이터
export const listItems: ListItem[] = [
  {
    id: 1,
    category: '#이색 체험',
    title: '#서귀포잠수함',
    url: '@/assets/Main_Theme/01.webp',
    contentId: 126665,
  },
  {
    id: 2,
    category: '#이색 체험',
    title: '#삼척 환선굴',
    url: '@/assets/Main_Theme/02.webp',
    contentId: 126729,
  },
  {
    id: 3,
    category: '#이색 체험',
    title: '#인제 스피디움',
    url: '@/assets/Main_Theme/03.webp',
    contentId: 2433873,
  },
  {
    id: 4,
    category: '#이색 체험',
    title: '#해운대 캡슐열차',
    url: '@/assets/Main_Theme/04.webp',
    contentId: 2672393,
  },
  {
    id: 5,
    category: '#이색 체험',
    title: '#대관령 양떼목장',
    url: '@/assets/Main_Theme/05.webp',
    contentId: 2789512,
  },
  {
    id: 6,
    category: '#이색 체험',
    title: '#단양 패러글라이딩',
    url: '@/assets/Main_Theme/06.webp',
    contentId: 2368508,
  },
  // contentId 수정해야 됨
  {
    id: 7,
    category: '#자연을 찾아 떠나는 자유여행',
    title: '#제주 백약이오름 ',
    url: '@/assets/Main_Theme/07.webp',
    contentId: 2731801,
  },
  {
    id: 8,
    category: '#자연을 찾아 떠나는 자유여행',
    title: '#창녕 우포늪',
    url: '@/assets/Main_Theme/08.webp',
    contentId: 126737,
  },
  {
    id: 9,
    category: '#자연을 찾아 떠나는 자유여행',
    title: '#태백산 눈꽃축제',
    url: '@/assets/Main_Theme/09.webp',
    contentId: 406912,
  },
  {
    id: 10,
    category: '#자연을 찾아 떠나는 자유여행',
    title: '#한려 해상 국립공원',
    url: '@/assets/Main_Theme/10.webp',
    contentId: 126014,
  },
  {
    id: 11,
    category: '#자연을 찾아 떠나는 자유여행',
    title: '# 화담숲 수선화 축제',
    url: '@/assets/Main_Theme/11.webp',
    contentId: 2810921,
  },
  {
    id: 12,
    category: '#자연을 찾아 떠나는 자유여행',
    title: '# 신안 1004요트',
    url: '@/assets/Main_Theme/12.webp',
    contentId: 2500717,
  },
  {
    id: 13,
    category: '#데이트 장소',
    title: '#서울 연남동',
    url: '@/assets/Main_Theme/13.webp',
    contentId: 2784040,
  },
  {
    id: 14,
    category: '#데이트 장소',
    title: '#부산 흰여울문화마을',
    url: '@/assets/Main_Theme/14.webp',
    contentId: 2684712,
  },
  {
    id: 15,
    category: '#데이트 장소',
    title: '#춘천 남이섬',
    url: '@/assets/Main_Theme/15.webp',
    contentId: 128019,
  },
  {
    id: 16,
    category: '#데이트 장소',
    title: '#파주 벽초지수목원',
    url: '@/assets/Main_Theme/16.webp',
    contentId: 128626,
  },
  {
    id: 17,
    category: '#데이트 장소',
    title: '#제주 이니스프리',
    url: '@/assets/Main_Theme/17.webp',
    contentId: 2894043,
  },
  {
    id: 18,
    category: '#데이트 장소',
    title: '#제천 의림지와 제림',
    url: '@/assets/Main_Theme/18.webp',
    contentId: 127804,
  },
  {
    id: 19,
    category: '#국내에서 즐기는 해외여행',
    title: '#가평 쁘티 프랑스',
    url: '@/assets/Main_Theme/19.webp',
    contentId: 604009,
  },
  {
    id: 20,
    category: '#국내에서 즐기는 해외여행',
    title: '#남해 독일마을',
    url: '@/assets/Main_Theme/20.webp',
    contentId: 129489,
  },
  {
    id: 21,
    category: '#국내에서 즐기는 해외여행',
    title: '#상소동 산림욕장',
    url: '@/assets/Main_Theme/21.webp',
    contentId: 1125480,
  },
  {
    id: 22,
    category: '#국내에서 즐기는 해외여행',
    title: '#인천 차이나타운',
    url: '@/assets/Main_Theme/22.webp',
    contentId: 264512,
  },
  {
    id: 23,
    category: '#국내에서 즐기는 해외여행',
    title: '# 용인 한국 민속촌',
    url: '@/assets/Main_Theme/23.webp',
    contentId: 2912454,
  },
  {
    id: 24,
    category: '#국내에서 즐기는 해외여행',
    title: '#구룡포 일본인 가옥거리',
    url: '@/assets/Main_Theme/24.webp',
    contentId: 1909659,
  },
];
